### ISSUE TITLE
关于演示代码的bug

### ISSUE THREAD

**Issue by qi0416** [X-Shi/Zoom-CAM#1]
您的演示代码main.py的46行
zoom_cams.append(activations[len(intermediate_layers)-i].cpu() * weights[i].cpu())
其中 [len(intermediate_layers)-i] 应该是[len(intermediate_layers)-i-1]，不然会超出列表范围

顺带询问一下对代码的不接，为啥我的weights是空列表
def save_weight(self, grad):
		self.weights.append(grad)
这个类函数没有运行过一次，是不是代码少了反向传播的步骤

**Comment by X-Shi** [comment]
Thank you for your interest and for pointing out the list bug.

As for your weights, have you modified your model into two parts: features and classifier? 
Because there are grad hooks at your desired layers, the function of 'save_weight' will append the gradients automatically. You can check line 20 of 'object_class.py' file.
